Repository DMSport/DMSport-Android, pull requests merged in 2022-10, with the labels that each got.

#2 Feature/1 splash activity
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/MainActivity.kt
  app/src/main/res/drawable/app_logo.png
  app/src/main/res/drawable/icon_splash.png
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가

#5 Feature/3_바텀_네비게이션_구현
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/BottomNavActivity.kt
  app/src/main/java/com/example/dmsport_android/MyPageFragment.kt
  app/src/main/java/com/example/dmsport_android/NoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/VoteFragment.kt
  app/src/main/res/drawable/ic_my_page.png
  app/src/main/res/drawable/ic_notice.png
  app/src/main/res/drawable/ic_vote.png
  app/src/main/res/drawable/ic_vote_selected.png
  app/src/main/res/drawable/item_selected_color.xml
  app/src/main/res/layout/activity_bottom_nav.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/menu/bottom_nav_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  local.properties
Labels: 기능 추가

#7 Feature/#4_로그인_구현
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/BaseActivity.kt
  app/src/main/java/com/example/dmsport_android/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/LoginRepository.kt
  app/src/main/java/com/example/dmsport_android/LoginRequest.kt
  app/src/main/java/com/example/dmsport_android/LoginViewModel.kt
  app/src/main/java/com/example/dmsport_android/MainActivity.kt
  app/src/main/java/com/example/dmsport_android/ServerApi.kt
  app/src/main/java/com/example/dmsport_android/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/Token.kt
  app/src/main/res/drawable/button_primary.xml
  app/src/main/res/drawable/button_white.xml
  app/src/main/res/drawable/edittext_courner.xml
  app/src/main/res/drawable/ic_splash.png
  app/src/main/res/drawable/ic_visible_off.png
  app/src/main/res/drawable/ic_visible_on.png
  app/src/main/res/font/black.ttf
  app/src/main/res/font/bold.ttf
  app/src/main/res/font/extrabold.ttf
  app/src/main/res/font/extralight.ttf
  app/src/main/res/font/light.ttf
  app/src/main/res/font/medium.ttf
  app/src/main/res/font/regular.ttf
  app/src/main/res/font/semibold.ttf
  app/src/main/res/font/thin.ttf
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: 문서 작성, 기능 추가

#10 #9_패키지_분할_및_코드_리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/LoginRepository.kt
  app/src/main/java/com/example/dmsport_android/LoginRequest.kt
  app/src/main/java/com/example/dmsport_android/ServerApi.kt
  app/src/main/java/com/example/dmsport_android/base/BaseActivity.kt
  app/src/main/java/com/example/dmsport_android/dto/request/LoginRequest.kt
  app/src/main/java/com/example/dmsport_android/dto/response/LoginResponse.kt
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/network/ServerApi.kt
  app/src/main/java/com/example/dmsport_android/repository/LoginRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/BottomNavActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/NoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/VoteFragment.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/util/Token.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/LoginViewModelFactory.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/menu/bottom_nav_item.xml
  app/src/main/res/values/strings.xml
  local.properties
Labels: 버그, 코드 리팩토링, 기능 수정

#13 Feature/#12_회원가입_퍼블리싱
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/base/BaseActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/RegisterActivity.kt
  app/src/main/java/com/example/dmsport_android/util/IntentUtil.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/util/Token.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_verify.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 코드 리팩토링, 기능 추가

#15 Feature/#14_회원가입_기능_구현
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/bindingadapter/BindingAdapter.kt
  app/src/main/java/com/example/dmsport_android/dto/request/DuplicateRequest.kt
  app/src/main/java/com/example/dmsport_android/dto/request/RegisterRequest.kt
  app/src/main/java/com/example/dmsport_android/dto/request/VerifyEmailRequest.kt
  app/src/main/java/com/example/dmsport_android/dto/request/VerifyRequest.kt
  app/src/main/java/com/example/dmsport_android/dto/response/RegisterResponse.kt
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/network/ServerApi.kt
  app/src/main/java/com/example/dmsport_android/repository/RegisterRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/RegisterActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/VerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/util/ResponseCode.kt
  app/src/main/java/com/example/dmsport_android/util/SnackBarUtil.kt
  app/src/main/java/com/example/dmsport_android/util/Token.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/RegisterViewModelFactory.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_verify.xml
  app/src/main/res/values/strings.xml
Labels: 버그, 코드 리팩토링, 기능 추가
