Repository DMSport/DMSport-Android, pull requests merged in 2022-11, with the labels that each got.

#16 #11_메인페이지_뷰_구현
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/base/BaseFragment.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/BottomNavActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/VoteFragment.kt
  app/src/main/res/drawable/vote_card_view_off.xml
  app/src/main/res/drawable/vote_card_view_on.xml
  app/src/main/res/drawable/vote_event_apply.xml
  app/src/main/res/drawable/vote_event_badminton.png
  app/src/main/res/drawable/vote_event_basketball.png
  app/src/main/res/drawable/vote_event_progressbar.xml
  app/src/main/res/drawable/vote_event_soccer.png
  app/src/main/res/drawable/vote_event_volleyball.png
  app/src/main/res/drawable/vote_selector_switch.xml
  app/src/main/res/drawable/vote_switch_off.xml
  app/src/main/res/drawable/vote_switch_on.xml
  app/src/main/res/drawable/vote_switch_thumb.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/list_vote.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 기능 추가

#18 (#17) 로그인 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/repository/LoginRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/LoginViewModelFactory.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
Labels: 기능 추가

#20 🔀 :: (#19) 코드 리팩토링
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/dto/request/VerifyRequest.kt
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/MainActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/RegisterActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/VerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/util/Token.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/LoginViewModelFactory.kt
  app/src/main/res/layout/activity_bottom_nav.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
Labels: 코드 리팩토링, 기능 수정

#23 🔀 :: (#22) 마이페이지 퍼블리싱
  app/src/main/res/drawable/background_corner.xml
  app/src/main/res/drawable/button_primary.xml
  app/src/main/res/drawable/button_white.xml
  app/src/main/res/drawable/edittext_courner.xml
  app/src/main/res/drawable/item_selected_color.xml
  app/src/main/res/drawable/mypage_arrow.png
  app/src/main/res/drawable/mypage_arrow_error.png
  app/src/main/res/drawable/vote_card_view_on.xml
  app/src/main/res/drawable/vote_event_apply.xml
  app/src/main/res/drawable/vote_event_progressbar.xml
  app/src/main/res/drawable/vote_switch_off.xml
  app/src/main/res/drawable/vote_switch_on.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/list_vote.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 코드 리팩토링, 퍼블리싱

#25 🔀 :: (#24) 마이페이지 기능 구현
  app/src/main/java/com/example/dmsport_android/dto/response/MyPageResponse.kt
  app/src/main/java/com/example/dmsport_android/network/ServerApi.kt
  app/src/main/java/com/example/dmsport_android/repository/MyPageRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/MainActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/MyPageViewModelFactory.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: 기능 추가

#29 🔀 :: (#28) 로그아웃 기능 구현
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/network/LoginApi.kt
  app/src/main/java/com/example/dmsport_android/network/MyPageApi.kt
  app/src/main/java/com/example/dmsport_android/network/RegisterApi.kt
  app/src/main/java/com/example/dmsport_android/repository/LoginRepository.kt
  app/src/main/java/com/example/dmsport_android/repository/MyPageRepository.kt
  app/src/main/java/com/example/dmsport_android/repository/RegisterRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: 기능 추가

#31 🔀 :: (#21) 비밀번호 변경 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/dto/request/EmailChangePwRequest.kt
  app/src/main/java/com/example/dmsport_android/dto/request/FindPwVerifyEmailRequest.kt
  app/src/main/java/com/example/dmsport_android/network/ServerApi.kt
  app/src/main/java/com/example/dmsport_android/repository/EmailChangePwRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/ChangePwVerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/EmailChangePwActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/EmailChangePwViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/EmailChangePwViewModelFactory.kt
  app/src/main/res/layout/activity_change_pw_verify.xml
  app/src/main/res/layout/activity_email_change_pw.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 기능 추가

#33 🔀 :: (#30) 회원탈퇴 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/dto/request/DeleteUserRequest.kt
  app/src/main/java/com/example/dmsport_android/network/LoginApi.kt
  app/src/main/java/com/example/dmsport_android/network/MyPageApi.kt
  app/src/main/java/com/example/dmsport_android/network/RegisterApi.kt
  app/src/main/java/com/example/dmsport_android/repository/LoginRepository.kt
  app/src/main/java/com/example/dmsport_android/repository/MyPageRepository.kt
  app/src/main/java/com/example/dmsport_android/repository/RegisterRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/DeleteUserActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/VerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/RegisterViewModel.kt
  app/src/main/res/drawable/delete_user_back.png
  app/src/main/res/layout/activity_delete_user.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 버그, 기능 추가

#35 🔀 :: (#34) 컨플릭트 수정 및 코드 리팩토링
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/network/MyPageApi.kt
  app/src/main/java/com/example/dmsport_android/network/ServerApi.kt
  app/src/main/java/com/example/dmsport_android/repository/EmailChangePwRepository.kt
  app/src/main/java/com/example/dmsport_android/repository/LoginRepository.kt
  app/src/main/java/com/example/dmsport_android/repository/MyPageRepository.kt
  app/src/main/java/com/example/dmsport_android/repository/RegisterRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/ChangePwVerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/DeleteUserActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/EmailChangePwActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/MainActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/RegisterActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/VerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/util/IntentUtil.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/util/SnackBarUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/EmailChangePwViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/EmailChangePwViewModelFactory.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/LoginViewModelFactory.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/MyPageViewModelFactory.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/RegisterViewModelFactory.kt
  app/src/main/res/layout/activity_change_pw_verify.xml
  app/src/main/res/layout/activity_email_change_pw.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_verify.xml
  app/src/main/res/values/style.xml
Labels: 버그, 코드 리팩토링

#37 🔀 :: (#36) 투표 조회 기능 구현
  app/src/main/java/com/example/dmsport_android/adapter/VoteListAdapter.kt
  app/src/main/java/com/example/dmsport_android/base/BaseActivity.kt
  app/src/main/java/com/example/dmsport_android/dto/response/VoteListResponse.kt
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/network/VoteApi.kt
  app/src/main/java/com/example/dmsport_android/repository/VoteListRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/DeleteUserActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/MainActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/RegisterActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/VerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/VoteFragment.kt
  app/src/main/java/com/example/dmsport_android/util/ConvertTextUtil.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/VoteListViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/VoteListViewModelFactory.kt
  app/src/main/res/drawable/vote_selector_switch.xml
  app/src/main/res/drawable/vote_switch_off.xml
  app/src/main/res/drawable/vote_switch_on.xml
  app/src/main/res/drawable/vote_switch_thumb.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/list_vote.xml
Labels: 코드 리팩토링, 기능 추가

#38 Feature/#32_비밀번호_변경_리팩토링
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/network/ChangePwApi.kt
  app/src/main/java/com/example/dmsport_android/repository/EmailChangePwRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/ChangePwVerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/EmailChangePwActivity.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/EmailChangePwViewModel.kt
  app/src/main/res/layout/activity_change_pw_verify.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/style.xml
Labels: 코드 리팩토링, 기능 수정

#42 비밀번호 변경 컨플릭트 수정 및 코드 리팩토링
  app/src/main/java/com/example/dmsport_android/dto/request/VerifyRequest.kt
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/repository/EmailChangePwRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/ChangePwVerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/EmailChangePwActivity.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/EmailChangePwViewModel.kt
Labels: 코드 리팩토링, 기능 수정

#44 🔀 :: (#41) 투표 조회 기능 수정
  app/src/main/java/com/example/dmsport_android/adapter/VoteListAdapter.kt
  app/src/main/java/com/example/dmsport_android/base/BaseFragment.kt
  app/src/main/java/com/example/dmsport_android/dto/response/MyPageResponse.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/VoteFragment.kt
  app/src/main/java/com/example/dmsport_android/util/ConvertTextUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/VoteListViewModel.kt
Labels: 기능 수정

#46 🔀 :: (#45) 투표 기능 구현
  app/src/main/java/com/example/dmsport_android/network/VoteApi.kt
  app/src/main/java/com/example/dmsport_android/repository/VoteListRepository.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/VoteListViewModel.kt
  app/src/main/res/layout/list_vote.xml
Labels: 기능 추가

#48 🔀 :: (#47) 로그인 후 비밀번호 변경 기능 구현
  app/src/main/java/com/example/dmsport_android/dto/request/ChagePasswordRequest.kt
  app/src/main/java/com/example/dmsport_android/network/ChangePwApi.kt
  app/src/main/java/com/example/dmsport_android/repository/ChangePasswordRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/ChangePwVerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/EmailChangePwActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/EmailChangePwViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/EmailChangePwViewModelFactory.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#50 🔀 :: (#49) 투표 내부 로직 버그 수정
  app/src/main/java/com/example/dmsport_android/viewmodel/VoteListViewModel.kt
Labels: 기능 수정

#52 🔀 :: (#43) 공지 목록 조회 UI 및 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/adapter/AllNoticeAdapter.kt
  app/src/main/java/com/example/dmsport_android/dto/response/AllNoticeResponse.kt
  app/src/main/java/com/example/dmsport_android/dto/response/RecentNoticeResponse.kt
  app/src/main/java/com/example/dmsport_android/network/ApiProvider.kt
  app/src/main/java/com/example/dmsport_android/network/NoticeApi.kt
  app/src/main/java/com/example/dmsport_android/repository/NoticeRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/EmailChangePwActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/MoreAllNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/fragment/NoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/NoticeViewModel.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/factory/NoticeViewModelFactory.kt
  app/src/main/res/drawable/all_notice_back.png
  app/src/main/res/layout/activity_more_all_notice.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/list_all_notice_more.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 기능 추가, 퍼블리싱

#54 🔀 :: (#53) 공지사항 상세보기 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/adapter/AllNoticeAdapter.kt
  app/src/main/java/com/example/dmsport_android/dto/response/DetailNoticeResponse.kt
  app/src/main/java/com/example/dmsport_android/network/NoticeApi.kt
  app/src/main/java/com/example/dmsport_android/repository/NoticeRepository.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/DetailNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/ui/activity/MoreAllNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/java/com/example/dmsport_android/viewmodel/NoticeViewModel.kt
  app/src/main/res/layout/activity_detail_notice.xml
  app/src/main/res/layout/activity_more_all_notice.xml
  app/src/main/res/layout/list_all_notice_more.xml
  app/src/main/res/values/style.xml
Labels: 기능 추가

#58 🔀 :: (#57) 최근 공지 조회 기능 구현
  app/src/main/java/com/example/dmsport_android/feature/notice/activity/MoreAllNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/adapter/AllNoticeAdapter.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/adapter/NoticeAdapter.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/fragment/NoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/model/RecentNoticeResponse.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/viewmodel/NoticeViewModel.kt
  app/src/main/res/layout/activity_more_all_notice.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/list_all_notice.xml
  app/src/main/res/layout/list_notice.xml
  app/src/main/res/values/style.xml
  gradle.properties
Labels: 코드 리팩토링, 기능 추가

#60 🔀 :: (#59) 공지사항 작성 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dmsport_android/base/BaseActivity.kt
  app/src/main/java/com/example/dmsport_android/base/BaseFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/deleteuser/DeleteUserActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/login/activity/LoginActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/dmsport_android/feature/mypage/fragment/MyPageFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/example/dmsport_android/feature/mypage/viewmodel/factory/MyPageViewModelFactory.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/activity/DetailNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/activity/MoreAllNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/fragment/CreateNoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/fragment/NoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/model/CreateNoticeRequest.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/viewmodel/NoticeViewModel.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/viewmodel/factory/NoticeViewModelFactory.kt
  app/src/main/java/com/example/dmsport_android/feature/vote/fragment/VoteFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/vote/repository/NoticeRepository.kt
  app/src/main/java/com/example/dmsport_android/network/NoticeApi.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/edittext_normal.xml
  app/src/main/res/drawable/edittext_notice.xml
  app/src/main/res/drawable/ic_create_notice.png
  app/src/main/res/layout/activity_more_all_notice.xml
  app/src/main/res/layout/dialog_create_notice.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 기능 추가

#62 🔀 :: (#61) 종목별 공지사항 전체 조회 기능 구현
  app/src/main/java/com/example/dmsport_android/feature/notice/activity/MoreAllNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/adapter/AllNoticeAdapter.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/adapter/NoticeAdapter.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/fragment/CreateNoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/fragment/NoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/model/NoticeListResponse.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/model/RecentNoticeResponse.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/viewmodel/NoticeViewModel.kt
  app/src/main/java/com/example/dmsport_android/feature/vote/repository/NoticeRepository.kt
  app/src/main/java/com/example/dmsport_android/network/NoticeApi.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/res/layout/activity_more_all_notice.xml
  app/src/main/res/layout/list_all_notice.xml
  app/src/main/res/layout/list_notice.xml
  app/src/main/res/values/strings.xml
Labels: 코드 리팩토링, 기능 추가, 기능 수정

#66 🔀 :: (#65) 공지사항 수정 기능 구현
  app/src/main/java/com/example/dmsport_android/feature/changepassword/activity/ChangePwVerifyActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/changepassword/activity/EmailChangePwActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/activity/DetailNoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/activity/NoticeActivity.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/adapter/NoticeAdapter.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/fragment/NoticeFragment.kt
  app/src/main/java/com/example/dmsport_android/feature/notice/viewmodel/NoticeViewModel.kt
  app/src/main/java/com/example/dmsport_android/feature/vote/repository/NoticeRepository.kt
  app/src/main/java/com/example/dmsport_android/network/NoticeApi.kt
  app/src/main/java/com/example/dmsport_android/util/DialogUtil.kt
  app/src/main/java/com/example/dmsport_android/util/SharedPreferenceUtil.kt
  app/src/main/res/layout/dialog_create_notice.xml
  app/src/main/res/values/strings.xml
Labels: 버그, 코드 리팩토링, 기능 추가, 기능 수정
